JAVA_HOME=/opt/jdk1.8.0_221
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin
PYTHON_HOME=/opt/Python-3.7.7
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin
SCALA_HOME=/opt/scala-2.11.8
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin
SBT_HOME=/opt/sbt-1.3.13
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin
JAVA_HOME=/opt/jdk1.8.0_221
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/opt/jdk1.8.0_221/bin
export HADOOP_HOME=/opt/hadoop-2.7.7
export HADOOP_INSTALL=
export HADOOP_MAPRED_HOME=
export HADOOP_COMMON_HOME=
export HADOOP_HDFS_HOME=
export YARN_HOME=
export HADOOP_COMMON_LIB_NATIVE_DIR=/lib/native
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/sbin:/bin
JAVA_HOME=/opt/jdk1.8.0_221
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/sbin:/bin:/opt/jdk1.8.0_221/bin
export HADOOP_HOME=/opt/hadoop-2.7.7
export HADOOP_INSTALL=/opt/hadoop-2.7.7
export HADOOP_MAPRED_HOME=/opt/hadoop-2.7.7
export HADOOP_COMMON_HOME=/opt/hadoop-2.7.7
export HADOOP_HDFS_HOME=/opt/hadoop-2.7.7
export YARN_HOME=/opt/hadoop-2.7.7
export HADOOP_COMMON_LIB_NATIVE_DIR=/opt/hadoop-2.7.7/lib/native
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/sbin:/bin:/opt/hadoop-2.7.7/sbin:/opt/hadoop-2.7.7/bin
JAVA_HOME=/opt/jdk1.8.0_221
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/sbin:/bin:/opt/hadoop-2.7.7/sbin:/opt/hadoop-2.7.7/bin:/opt/jdk1.8.0_221/bin
export HADOOP_HOME=/opt/hadoop-2.7.7
export HADOOP_INSTALL=/opt/hadoop-2.7.7
export HADOOP_MAPRED_HOME=/opt/hadoop-2.7.7
export HADOOP_COMMON_HOME=/opt/hadoop-2.7.7
export HADOOP_HDFS_HOME=/opt/hadoop-2.7.7
export YARN_HOME=/opt/hadoop-2.7.7
export HADOOP_COMMON_LIB_NATIVE_DIR=/opt/hadoop-2.7.7/lib/native
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/sbin:/bin:/opt/hadoop-2.7.7/sbin:/opt/hadoop-2.7.7/bin:/opt/hadoop-2.7.7/sbin:/opt/hadoop-2.7.7/bin
JAVA_HOME=/opt/jdk1.8.0_221
export PATH=/home/frederick/anaconda3/bin:/home/frederick/anaconda3/condabin:/home/frederick/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin
